name: peqing
description: "PENS QR Grading"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  iconsax: ^0.0.8
  http: ^1.2.1
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  go_router: ^14.1.1
  flutter_svg: ^2.0.10+1
  cupertino_radio_choice: ^1.0.2
  flutter_sliding_up_panel: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: "Plus Jakarta Sans"
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

flutter_native_splash:
  color: "#FCFBF7"
  image: assets/icons/lounch-icon.png
  color_dark: "#FCFBF7"
  image_dark: assets/icons/lounch-icon.png
  android_12:
    image: assets/icons/lounch-icon.png
    icon_background_color: "#FCFBF7"
    image_dark: assets/icons/lounch-icon.png
    icon_background_color_dark: "#FCFBF7"
  web: false

flutter_launcher_icons:
  image_path_android: "assets/icons/lounch-icon.png"
  image_path_ios: "assets/icons/lounch-icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/icons/lounch-icon.png"
  adaptive_icon_background: "assets/icons/background-peqing-icon.png"
  web:
    generate: true
    image_path: "assets/icons/lounch-icon.png"
    background_color: "#ff3838"
    theme_color: "#ff3838"
  windows:
    generate: true
    image_path: "assets/icons/lounch-icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/lounch-icon.png"
