name: peqing
description: "PENS QR Grading"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  iconsax: ^0.0.8
  http: ^1.2.1
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#FCFBF7"
  image: assets/images/logo-splash.png
  color_dark: "#FCFBF7"
  image_dark: assets/images/logo-splash.png
  android_12:
    image: assets/images/logo-splash.png
    icon_background_color: "#FCFBF7"
    image_dark: assets/images/logo-splash.png
    icon_background_color_dark: "#FCFBF7"
  web: false

flutter_launcher_icons:
  image_path_android: "assets/icons/peqing-icon.png"
  image_path_ios: "assets/icons/peqing-icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/icons/peqing-icon.png"
  adaptive_icon_background: "assets/icons/background-peqing-icon.png"
  web:
    generate: true
    image_path: "assets/icons/peqing-icon.png"
    background_color: "#ff3838"
    theme_color: "#ff3838"
  windows:
    generate: true
    image_path: "assets/icons/peqing-icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/peqing-icon.png"
